# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: FSRmsg.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x46SRmsg.proto\x12\x08pyFSRray\"+\n\x07\x46SRData\x12\r\n\x05value\x18\x01 \x01(\t\x12\x11\n\ttimestamp\x18\x02 \x01(\t\"@\n\x06\x46SRMsg\x12\x11\n\tsensor_id\x18\x01 \x01(\x05\x12#\n\x08\x66sr_data\x18\x02 \x03(\x0b\x32\x11.pyFSRray.FSRDatab\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'FSRmsg_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _FSRDATA._serialized_start=26
  _FSRDATA._serialized_end=69
  _FSRMSG._serialized_start=71
  _FSRMSG._serialized_end=135
# @@protoc_insertion_point(module_scope)
